### ISSUE TITLE
Fix overflows in consent screen

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-engineblock#1324]
The consent screen should handle the overflow of the identifier better than this:
![Screenshot 2024-09-16 at 13 29 36](https://github.com/user-attachments/assets/0bd30253-f6d4-4847-bc82-d6e8299d29d6)

I propose to add 
```css
element {
  text-overflow: ellipsis;
  text-wrap: nowrap;
  overflow: hidden;
}
```
on this element (not on the other attributes like name etc), which results in:
![Screenshot 2024-09-16 at 13 35 19](https://github.com/user-attachments/assets/0cb20916-058d-4669-89bf-7bcb85be1a9a)

If the info panel is opened, we should show the full id
![Screenshot 2024-09-16 at 13 36 56](https://github.com/user-attachments/assets/8974b803-f1de-4b98-af46-7327558e5a1e)
 again.
