### ISSUE TITLE
Make wiki link configurable on feedback page

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-engineblock#1578]
[This issue is imported from pivotal - Originaly created at May 1, 2019 by bstrooband](https://www.pivotaltracker.com/story/show/165742913)

When a wiki url is configured we should show the wiki link on the feedback page in the footer (as a button). This feature is partly implemented, as in: the styling is prepared to show 1, 2 or 3 buttons.

We need to verify if this needs to be a new Wiki url, or if one of the existing support urls that are already configurable can be reused.

Diverged from: #164121204
Estimation: 2 - 4h

**Implementation details**

The feedback links can be configured in the parameters.yml. An example configuration can be found below. 

```yaml
error_feedback:
    wiki_links:
        # 1. Fallback
        fallback: 
            en: \'https://example.org/main\'
            nl: \'https://example.org/main\'
            pt: \'https://example.org/main\'
        # 2. Specified Wiki links
        specified:
            received_invalid_response:
                en: \'https://example.org/wiki/page1\'
                nl: \'https://example.nl/wiki/page1\'
                pt: \'https://example.pt/wiki/page1\'
            received_invalid_signed_response:
                # 3. Multilingual supporting fallback when translation is not specified
                en: \'https://example.org/wiki/page1\'
            clock_issue:
                en: \'https://example.org/wiki/page1\'
```

1. A fallback link can be configured. This is only a fallback for the specified Wikilinks that do not have a suitable translation, but are defined. The fallback links are specified in a multilingual manner.
2.  The Wiki links are also specified in a multilingual fashion. And the Wiki links are identified by the page identifier. This identifier matches the route name found in the feedback.yml error page routing. When a route is not set with a custom wiki link, no wiki link button will be rendered. The fallback link is not displayed!
3. Not all languages need to be configured. When a page is set with a translation, but one or more languages are missing. For those missing languages the `fallback` link is rendered.

**Comment by phavekes** [comment]
@arnoutt I assume this would be shown on all error pages if a link is set in the currently active translation file? (bstrooband - May 1, 2019)

**Comment by phavekes** [comment]
Yes! (Arnout Terpstra - May 1, 2019)

**Comment by phavekes** [comment]
In the ideal world the link to use would be specific to the error screen.

In the most perfect ideal world the link would also be specific to the language. (Thijs Kinkhorst - Jul 23, 2019)

**Comment by phavekes** [comment]
We could create a dedicated YAML config file for this as configuring this in the INI format will be tedious.

Here we could configure:

1. A default wiki link that is displayed as a fallback
2. A mapping of error page identifier (uri/..) mapped to a wiki page link
3. If need be, that could be made to be i18nized

```yaml
feedback:
    wiki-links:
        default: "https://link-to-your-default-wiki.org/index"
        specified:
            session-lost: "https://example.org/wiki/page1"
            invalid-acs-location: "https://example.org/wiki/page2"            
```

Or internationalized:

```yaml
feedback:
    wiki-links:
        default: "https://link-to-your-default-wiki.org/index"
        specified:
            session-lost: 
                en: "https://example.org/wiki/page1"
                nl: "https://example.nl/wiki/page1"
            invalid-acs-location: 
                en: "https://example.org/wiki/page2"
                nl: "https://example.nl/wiki/page2"
```

@arnoutt Both the options are simple to realize. But the question is which one is preferable? (Michiel Kodde - Aug 13, 2019)
